config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :reminders, :except => [:edit, :update]

  root to: "reminders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user

  validates :title, :presence => true
  validates :description, :presence => true
  validates :remind_at, :presence => true

  validate :reminder_after_2_days

  private

  def reminder_after_2_days
    if remind_at.present? && remind_at < 2.days.from_now
      errors.add(:remind_at, "date must be after 2 days")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reminders, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Raises exception if we forgot to call authorize in any action except
  # Case 1: If index, new or create action
  # Case 2: If devise controller actions
  after_action :verify_authorized, :except => [:index, :new, :create]
  after_action :verify_authorized, :unless => :devise_controller?

  rescue_from Pundit::NotAuthorizedError, :with => :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."

    redirect_to(request.referrer || root_path)
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!

  # Throw exception if pundit authorize function not used in any action
  after_action :verify_authorized

  before_action :set_reminder, only: [:show, :destroy]

  # GET /reminders
  def index
    @reminders = current_user.reminders

    authorize Reminder 
  end

  # GET /reminders/1
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new

    authorize @reminder
  end

  # POST /reminders
  def create
    @reminder = Reminder.new(reminder_params)

    @reminder.user = current_user

    authorize @reminder

    if @reminder.save
      ReminderJob.set(:wait_until => @reminder.remind_at.to_i)
                 .perform_later(@reminder)

      redirect_to @reminder, notice: 'Reminder was successfully created.'
    else
      render :new
    end
  end

  # DELETE /reminders/1
  def destroy
    @reminder.destroy
    redirect_to reminders_url, notice: 'Reminder was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])

      authorize @reminder
    end

    # Only allow a trusted parameter "white list" through.
    def reminder_params
      params.require(:reminder).permit(:title, :description, :remind_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
  def format_date(date)
    return if date.nil?

    date.strftime("%F %H:%M")
  end
end

app/views/layouts/_header.html.haml
.header.sticky-top.d-block.bg-primary
  .container.py-3
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
      .container-fluid
        = link_to 'Home', reminders_path, class: 'navbar-brand'

        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'd-flex justify-content-end btn btn-outline-light'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title ReminderApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = render 'layouts/header'

    .container.py-3
      %p#notice
        = notice

      %p#alert
        = alert

      = yield

app/views/reminders/_form.html.haml
= form_for @reminder do |f|
  .row.mb-3
    .col
      - if @reminder.errors.any?
        #error_explanation
          %h2= "#{pluralize(@reminder.errors.count, "error")} prohibited this reminder from being saved:"
          %ul
            - @reminder.errors.full_messages.each do |message|
              %li= message

  .row.mb-3
    = f.label :title, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.text_field :title, :required => "required", class: 'form-control'
  .row.mb-3
    = f.label :description, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.text_area :description, :required => "required", class: 'form-control'
  .row.mb-3
    = f.label :remind_at, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.text_field :remind_at, :value => format_date(@reminder.remind_at), :data => { :behavior => 'flatpickr' }, class: 'form-control'
  .row.mb-3
    .col-md-10.offset-2
      = link_to 'Cancel', reminders_path, class: 'btn btn-secondary'
      = f.submit 'Save', class: 'btn btn-primary'

app/views/reminders/_reminder.html.haml
%tr
  %td= reminder.title
  %td= reminder.description
  %td= reminder.remind_at
  %td
    = link_to 'Show', reminder, class: 'btn btn-sm btn-secondary'
    = link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/reminders/index.html.haml
%h1 Reminders

%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Description
      %th Remind at
      %th Actions

  %tbody
    = render @reminders

%br

= link_to 'New Reminder', new_reminder_path, class: 'btn btn-primary'

app/views/reminders/new.html.haml
%h1 New reminder

= render 'form'

app/views/reminders/show.html.haml
%h1 Reminder

%p
  %b Title:
  = @reminder.title
%p
  %b Description:
  = @reminder.description
%p
  %b Remind at:
  = format_date(@reminder.remind_at)

= link_to 'Back', reminders_path, class: 'btn btn-secondary'